# Generated by Django 3.1.1 on 2020-09-29 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myfile',
            name='original',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='myfile',
            name='processed',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
